// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.VowelCounter
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("vowels")]
        public long Vowels { get; set; }

        [JsonProperty("consonants")]
        public long Consonants { get; set; }

        [JsonProperty("totalLetters")]
        public long TotalLetters { get; set; }

        [JsonProperty("vowelPercentage")]
        public double VowelPercentage { get; set; }

        [JsonProperty("consonantPercentage")]
        public double ConsonantPercentage { get; set; }

        [JsonProperty("vowelBreakdown")]
        public VowelBreakdown VowelBreakdown { get; set; }

        [JsonProperty("textLength")]
        public long TextLength { get; set; }
    }

    public partial class VowelBreakdown
    {
        [JsonProperty("a")]
        public long A { get; set; }

        [JsonProperty("e")]
        public long E { get; set; }

        [JsonProperty("i")]
        public long I { get; set; }

        [JsonProperty("o")]
        public long O { get; set; }

        [JsonProperty("u")]
        public long U { get; set; }
    }
}
